/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.netris.nativesocket;

public interface senderConstants {
  public final static int MAX_BUFFER_SIZE = senderJNI.MAX_BUFFER_SIZE_get();
  public final static int MAX_LOG_MESSAGE_LENGTH = senderJNI.MAX_LOG_MESSAGE_LENGTH_get();
}
