/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.netris.posixsocket;

public class senderJNI {
  public final static native int MAX_BUFFER_SIZE_get();
  public final static native int MAX_LOG_MESSAGE_LENGTH_get();
  public final static native long new_SenderSocket();
  public final static native void delete_SenderSocket(long jarg1);
  public final static native boolean SenderSocket_connectToHost(long jarg1, SenderSocket jarg1_, String jarg2, int jarg3);
  public final static native boolean SenderSocket_closeSocket(long jarg1, SenderSocket jarg1_);
  public final static native int SenderSocket_sendToHost(long jarg1, SenderSocket jarg1_, byte[] jarg2);
  public final static native int SenderSocket_readFromHost(long jarg1, SenderSocket jarg1_, byte[] jarg2);
}
